import { Router } from 'express';
import Result from '../utils/result';
const router: Router = Router();

router.get('/1223123', async (req: any, res) => {
    try {
        const info = {
            icon: 'https://asset.si.online/8f4eceb475d266e748e4bec810c8b266.png',
            label: 'GPU Cloud Mining',
            title: 'H100-1',
            description: 'Buy GPU-based Node H100-1',
            links: {
                actions: [
                    {
                        label: '1 份',
                        href: '/api/transaction/send?amount=1&id=91313b6a0b&debug=undefined',
                    },
                    { label: '2 份', href: '/api/transaction/send?amount=2&id=91313b6a0b&debug=undefined' },
                    { label: '3 份', href: '/api/transaction/send?amount=3&id=91313b6a0b&debug=undefined' },
                    { href: '/api/transaction/send?amount={amount}&id=91313b6a0b&debug=undefined', label: 'Buy', parameters: [{ name: 'amount', label: 'Enter the number of nodes' }] },
                ],
            },
        };
        res.send(info);
    } catch (e: any) {
        res.send(Result.err(500, e.message || String(e)));
    }
});

router.get('/transfer', async (req: any, res) => {
    try {
        const info = {
            icon: 'https://asset.si.online/c43cd76c060245b794b0d544ecd83f04.png',
            label: 'Donate SOL',
            title: 'Transfer',
            description: '拯救许皮带',
            links: {
                actions: [
                    // {
                    //     label: 'Include message',
                    //     href: `/api/transaction/send?amount={amount}&memo={memo}&debug=undefined`,
                    //     parameters: [
                    //         {
                    //             name: 'memo',
                    //             label: 'Enter your message',
                    //             required: true,
                    //         },
                    //     ],
                    // },
                    {
                        label: 'Send SOL',
                        href: `/api/transaction/send?amount={amount}&memo={memo}&debug=undefined`,
                        parameters: [
                            {
                                name: 'amount',
                                label: 'Enter the amount of SOL to send',
                                required: true,
                            },
                        ],
                    },
                ],
            },
        };
        res.send(info);
    } catch (e: any) {
        res.send(Result.err(500, e.message || String(e)));
    }
});

export default router;

const a = {
    actions: [
        { host: 'action.3.land', state: 'trusted' },
        { host: 'action.solscan.io', state: 'trusted' },
        { host: 'actions-basics.pages.dev', state: 'trusted' },
        { host: 'actions.dialect.to', state: 'trusted' },
        { host: 'actions.magicblock.app', state: 'trusted' },
        { host: 'actions.mcdegen.xyz:8444', state: 'trusted' },
        { host: 'actions.sonar.watch', state: 'trusted' },
        { host: 'actions.swissborg.com', state: 'trusted' },
        { host: 'alldomains.id', state: 'trusted' },
        { host: 'api-main-mainnet.dreader.io', state: 'trusted' },
        { host: 'api.askanon.fun', state: 'trusted' },
        { host: 'api.genopets.me', state: 'trusted' },
        { host: 'api.mallow.art', state: 'trusted' },
        { host: 'api.purebet.io', state: 'trusted' },
        { host: 'api.seer.coinhall.org', state: 'trusted' },
        { host: 'api.spherepay.co', state: 'trusted' },
        { host: 'api.thesendcoin.com', state: 'trusted' },
        { host: 'api.torque.so', state: 'trusted' },
        { host: 'app.circuit.trade', state: 'trusted' },
        { host: 'app.drift.trade', state: 'trusted' },
        { host: 'app.jibbers.io', state: 'trusted' },
        { host: 'app.jogojogo.game', state: 'trusted' },
        { host: 'app.solayer.org', state: 'trusted' },
        { host: 'askorb.xyz', state: 'trusted' },
        { host: 'backend.gh0stlabs.io', state: 'trusted' },
        { host: 'blink-flip.onrender.com', state: 'trusted' },
        { host: 'blink.bladerite.io', state: 'trusted' },
        { host: 'blink.foresightnews.pro', state: 'trusted' },
        { host: 'blink.futureprotocol.io', state: 'trusted' },
        { host: 'blink.lulo.fi', state: 'trusted' },
        { host: 'blink.sunrisestake.com', state: 'trusted' },
        { host: 'blink2earn.com', state: 'trusted' },
        { host: 'blinkbash.daoplays.org', state: 'trusted' },
        { host: 'blinkeditor.com', state: 'trusted' },
        { host: 'blinkgenerator.com', state: 'trusted' },
        { host: 'blinks-inspector.vercel.app', state: 'trusted' },
        { host: 'blinks-poc-dialect.vercel.app', state: 'malicious' },
        { host: 'blinks.alphabatem.io', state: 'trusted' },
        { host: 'blinks.cubik.so', state: 'trusted' },
        { host: 'blinks.prooflab.cc', state: 'trusted' },
        { host: 'blinks.solanahub.app', state: 'trusted' },
        { host: 'blinks.xyz', state: 'trusted' },
        { host: 'blnk.fun', state: 'trusted' },
        { host: 'cleanit.thesendcoin.com', state: 'trusted' },
        { host: 'death.breadheads.io', state: 'trusted' },
        { host: 'decod3rs.com', state: 'trusted' },
        { host: 'dewicats.xyz', state: 'trusted' },
        { host: 'dial.to', state: 'trusted' },
        { host: 'famousfoxes.com', state: 'trusted' },
        { host: 'fastmind.app', state: 'trusted' },
        { host: 'greed.academy', state: 'trusted' },
        { host: 'hedgehog.markets', state: 'trusted' },
        { host: 'jupswap.monstre.net', state: 'trusted' },
        { host: 'launchmynft.io', state: 'trusted' },
        { host: 'magicedennss.it', state: 'malicious' },
        { host: 'mainnet.underdogprotocol.com', state: 'trusted' },
        { host: 'mutantlabs.xyz', state: 'trusted' },
        { host: 'nick.af', state: 'trusted' },
        { host: 'nxfinance.io', state: 'trusted' },
        { host: 'p2p-blinks-psi.vercel.app', state: 'trusted' },
        { host: 'paragon.gdn', state: 'trusted' },
        { host: 'phaselabs.io', state: 'trusted' },
        { host: 'predict.solcasino.io', state: 'trusted' },
        { host: 'proofpass.xyz', state: 'trusted' },
        { host: 'ridetheblink.blinkgames.dev', state: 'trusted' },
        { host: 'sentinelactionfund.dial.to', state: 'trusted' },
        { host: 'share.raydium.io', state: 'trusted' },
        { host: 'sniper.xyz', state: 'trusted' },
        { host: 'sns-actions.bonfida.com', state: 'trusted' },
        { host: 'solactions.fun', state: 'trusted' },
        { host: 'solana-actions.vercel.app', state: 'trusted' },
        { host: 'solana.playspokemon.com', state: 'trusted' },
        { host: 'solcasino.io', state: 'trusted' },
        { host: 'solfate.com', state: 'trusted' },
        { host: 'soltip.me', state: 'trusted' },
        { host: 'spsblink.runepunk.gg', state: 'trusted' },
        { host: 'squads-actions-poc.vercel.app', state: 'trusted' },
        { host: 'stake.superfast.org', state: 'trusted' },
        { host: 't22.io', state: 'trusted' },
        { host: 'tensor.dial.to', state: 'trusted' },
        { host: 'theportal.to', state: 'trusted' },
        { host: 'tiplink.io', state: 'trusted' },
        { host: 'truffle.wtf', state: 'trusted' },
        { host: 'tug-of-war.magicblock.app', state: 'trusted' },
        { host: 'www.aeropool.io', state: 'trusted' },
        { host: 'www.blinks.xyz', state: 'trusted' },
        { host: 'www.blnk.fun', state: 'trusted' },
        { host: 'www.dewicats.xyz', state: 'trusted' },
        { host: 'www.dial.to', state: 'trusted' },
        { host: 'www.launchmynft.io', state: 'trusted' },
        { host: 'www.mutantlabs.xyz', state: 'trusted' },
        { host: 'www.okx.com', state: 'trusted' },
        { host: 'www.phaselabs.io', state: 'trusted' },
        { host: 'www.sniper.xyz', state: 'trusted' },
        { host: 'www.soltip.me', state: 'trusted' },
        { host: 'www.t22.io', state: 'trusted' },
    ],
    websites: [
        { host: '3.land', state: 'trusted' },
        { host: 'actions.dialect.to', state: 'trusted' },
        { host: 'alldomains.id', state: 'trusted' },
        { host: 'app.circuit.trade', state: 'trusted' },
        { host: 'app.drift.trade', state: 'trusted' },
        { host: 'app.jogojogo.game', state: 'trusted' },
        { host: 'app.meteora.ag', state: 'trusted' },
        { host: 'app.realms.today', state: 'trusted' },
        { host: 'app.sanctum.so', state: 'trusted' },
        { host: 'askanon.fun', state: 'trusted' },
        { host: 'askorb.xyz', state: 'trusted' },
        { host: 'blink2earn.com', state: 'trusted' },
        { host: 'blinkeditor.com', state: 'trusted' },
        { host: 'blinks.prooflab.cc', state: 'trusted' },
        { host: 'blnk.fun', state: 'trusted' },
        { host: 'coinhall.org', state: 'trusted' },
        { host: 'cubik.so', state: 'trusted' },
        { host: 'death.breadheads.io', state: 'trusted' },
        { host: 'decod3rs.com', state: 'trusted' },
        { host: 'dev.helius.xyz', state: 'trusted' },
        { host: 'dial.to', state: 'trusted' },
        { host: 'dreader.io', state: 'trusted' },
        { host: 'famousfoxes.com', state: 'trusted' },
        { host: 'fastmind.app', state: 'trusted' },
        { host: 'greed.academy', state: 'trusted' },
        { host: 'hedgehog.markets', state: 'trusted' },
        { host: 'hub.accessprotocol.co', state: 'trusted' },
        { host: 'jup.ag', state: 'trusted' },
        { host: 'launchmynft.io', state: 'trusted' },
        { host: 'lulo.fi', state: 'trusted' },
        { host: 'mcdegen.xyz', state: 'trusted' },
        { host: 'nick.af', state: 'trusted' },
        { host: 'nxfinance.io', state: 'trusted' },
        { host: 'paragon.gdn', state: 'trusted' },
        { host: 'phantom.app', state: 'trusted' },
        { host: 'rafffle.famousfoxes.com', state: 'trusted' },
        { host: 'raydium.io', state: 'trusted' },
        { host: 'realms.today', state: 'trusted' },
        { host: 'ridetheblink.blinkgames.dev', state: 'trusted' },
        { host: 'sentinelactionfund.com', state: 'trusted' },
        { host: 'solactions.fun', state: 'trusted' },
        { host: 'solanahub.app', state: 'trusted' },
        { host: 'solfate.com', state: 'trusted' },
        { host: 'solscan.io', state: 'trusted' },
        { host: 'spherepay.co', state: 'trusted' },
        { host: 'stake.superfast.org', state: 'trusted' },
        { host: 'theportal.to', state: 'trusted' },
        { host: 'tiplink.io', state: 'trusted' },
        { host: 'truffle.wtf', state: 'trusted' },
        { host: 'tug-of-war.magicblock.app', state: 'trusted' },
        { host: 'www.aeropool.io', state: 'trusted' },
        { host: 'www.dewicats.xyz', state: 'trusted' },
        { host: 'www.helium.com', state: 'trusted' },
        { host: 'www.mallow.art', state: 'trusted' },
        { host: 'www.mutantlabs.xyz', state: 'trusted' },
        { host: 'www.okx.com', state: 'trusted' },
        { host: 'www.phaselabs.io', state: 'trusted' },
        { host: 'www.sniper.xyz', state: 'trusted' },
        { host: 'www.soltip.me', state: 'trusted' },
        { host: 'www.t22.io', state: 'trusted' },
        { host: 'www.tensor.trade', state: 'trusted' },
    ],
    interstitials: [
        { host: 'actions.dialect.to', state: 'trusted' },
        { host: 'dial.to', state: 'trusted' },
        { host: 'nick.af', state: 'trusted' },
        { host: 'www.dial.to', state: 'trusted' },
    ],
};
